@include('layouts.partial.header_sampletemplate')
@include('layouts.partial.nav_sampletemplate')
@yield('script')
@yield('page_script')
@yield('content')
@include('layouts.partial.footer_sampletemplate')
@include('sweet::alert')
